### ISSUE TITLE
Update TCPDF to the latest version

### ISSUE THREAD

**Issue by guicara** [spipu/html2pdf#29] opened 2015-11-24 14:00 UTC
Thank you for your work, html2pdf is a great tool!

Is there any particular reason why an old version of TCPDF is used? The version 5.0.002 was released 5 years ago (https://github.com/tecnickcom/TCPDF/blob/develop/CHANGELOG.TXT). 

Can you update TCPDF to version 6.x, or add TCPDF as a dependency in the composer.json file?

Regards,
Guillaume

**Comment by fagundes** [comment] 2015-12-11 01:58
:+1:

**Comment by boussou** [comment] 2015-12-11 06:45
from my own tests, the most recent version you could use without regression is  _tcpdf_5_7_003
the latter versions of tcpdf has important changes in its internals.

**Comment by spipu** [comment] 2015-12-11 10:20
yes, and this is the pb...

i have not time to do this big update to v6.x :(

**Comment by guicara** [comment] 2015-12-11 10:43
Hello all,

At least could we upgrade TCPDF to version 5.7.003 by:

* Deleting the "_tcpdf_5.0.002" folder
* Updating the composer.json file to require TCPDF package in version 5.7.003
* Changing the value of HTML2PDF_USED_TCPDF_VERSION constant in html2pdf.class.php
* Changing the path of TCPDF in tcpdfConfig.php and myPdf.class.php

What do you think about it?

**Comment by GuillaumeMB** [comment] 2015-12-11 11:13
@boussou Do you know if the version 5.9.206 of TCPDF will work with html2pdf?
Because the following fork of html2pdf use this version: https://github.com/iafan/html2pdf

**Comment by guicara** [comment] 2015-12-11 11:14
@boussou Do you know if the version 5.9.206 of TCPDF will work with html2pdf?
Because the following fork of html2pdf use this version: https://github.com/iafan/html2pdf

**Comment by boussou** [comment] 2015-12-11 12:04
it won't. 
I tried it and experienced "white page" instead of expected pdfs

**Comment by juchi** [comment] 2015-12-11 13:53
Hi,
I have discussed with @spipu about this topic and we agreed this is the next important update to bring to this library.
Upgrading to tcpdf 5.7 is feasible but as the official package does not exist on packagist in this version (minimum is 6.0.13) we'd need to do more work so I guess it would indeed be better to go to version 6 all at once.
I have tested locally the upgrade to 6.0 and it seems to be working on all the example scripts provided by @spipu (no PHP errors), I will go through the final pdf files then to check that the rendering is correct and fix the code where needed, hopefully this won't take too much time.
When this is done, maybe @boussou you can check with your use case to see if you still experience the white pages problem and we can then move forward.

**Comment by boussou** [comment] 2015-12-11 14:06
Sure, that would be great.

btw, I saw no advantage using the 6.x line, because the font subsetting was not working - I mean reducing the size of pdfs-and maybe it has potential memory leaks when you generate something like 5000 pages.
No improvement on performance neither, which was the purpose of my tests several months ago

**Comment by fagundes** [comment] 2015-12-11 14:31
What do you guys think about create a new branch like `develop` to receive our PR's to create and fix this update?

Changing subject, since we are talking about major changes, there are 2 more:
 - create unit tests it should help next importants updates.
 - update to php 5.4+ (php 5.4 is already deprecated).

[PHP Supported Versions](http://php.net/supported-versions.php)

**Comment by spipu** [comment] 2015-12-11 14:47
@Juchi : about TCPDF update, could you push your work, so that i will also test, and see if i have time to help :)

**Comment by spipu** [comment] 2015-12-11 14:48
for information : @juchi is now an official contributor on the github html2pdf project : he has the push right

**Comment by juchi** [comment] 2015-12-11 14:48
@fagundes I will create some dedicated issues to talk about these topics

**Comment by juchi** [comment] 2015-12-11 14:54
@spipu you can check it on the branch update_tcpdf

**Comment by boussou** [comment] 2015-12-11 15:49
Good news.

If you share the branch, I'll help on it too.

@fagundes I would prefer sticking to 5.3 unless there is a good reason for setting 5.4 because I have some legacy apps on prod ;-)

btw if the min requirement is 5.3, it will work up to PHP7 right?
;-)

**Comment by juchi** [comment] 2015-12-15 15:23
Hi all,
The master branch has been updated with tcpdf 6.2 (installed through composer) and the resulting bugs should have been resolved. The example files look the same as before so you shouldn't encounter issues if you update. If you do, please report them and we'll investigate and fix them.

Version 4.5.0 of TCPDF will be release soon unless some major bug shows up from your tests.

**Comment by GuillaumeMB** [comment] 2015-12-15 15:27
That's great news!

**Comment by guicara** [comment] 2015-12-15 15:28
That's great news!

**Comment by fagundes** [comment] 2015-12-16 23:00
Shouldn't the v4.5 branch be a tag instead? So packagist can see it as a version.

Any way, we can close it.

**Comment by juchi** [comment] 2015-12-17 09:18
Yes we'll release the 4.5.0 tag at the end of the week, the 4.5 branch is here for updates (4.5.x) in case we need to do some afterwards.

**Comment by fagundes** [comment] 2015-12-17 15:27
Ok. I understood!

**Comment by juchi** [comment] 2015-12-18 19:42
Tag v4.5.0 has just been pushed so Html2Pdf with the latest version of Tcpdf is now officially available !

**Closed** 2015-12-19 10:20 UTC

**Comment by MarceloCacereVi** [comment] 2023-09-21 22:39
Hello geniuses,
Could someone explain to me what the process is to update my project's library?
I was using _tcpdf_5.0.002 which worked quite well, but when changing
hosting, the PHP version was updated and the reports stopped working.
Thank you

**Comment by Ramadhaniyanto19** [comment] 2025-05-20 15:47
> Hello geniuses, Could someone explain to me what the process is to update my project's library? I was using _tcpdf_5.0.002 which worked quite well, but when changing hosting, the PHP version was updated and the reports stopped working. Thank you ![reporte](https://github.com/spipu/html2pdf/assets/138160209/c65d2751-6174-4956-8eb1-0c02e6e84bdb)

bro you can find how to fix this? because i have same problem
