### ISSUE TITLE
Displaying <table> during generation

### ISSUE THREAD

**Issue by arshad95** [spipu/html2pdf#425] opened 2018-12-24 15:01 UTC
Hello,

When generating my pdf I have an error in the layout.
I generated a pdf containing several tables that appear one after the other (see link -> picture: content court), the problem is that if the content of my second table is short, it is displayed correctly to following the first. But if the content of my second table is long, HTML2PDF will skip a page after displaying my first table and displays the second on a second page (see image link -> long content).

But I would like that, no matter the size of my second table this one is always displayed after my second without skipping page.

Link to the drive or find the pictures : https://drive.google.com/open?id=1OwHAn_rvfGeS73hIWg-M3IUKvGXvwmJZ

**Comment by LittleBigFox** [comment] 2018-12-27 07:31
Hi!

Html2PDF uses the largest cell size to calculate what goes on one page or another.

If you want two tables to follow each other, you must delete the top table, replacing it with a div for example.

Regards,
LBF

**Comment by arshad95** [comment] 2018-12-28 08:36
> 
> 
> Hi!
> 
> Html2PDF uses the largest cell size to calculate what goes on one page or another.
> 
> If you want two tables to follow each other, you must delete the top table, replacing it with a div for example.
> 
> Regards,
> LBF

Thanks for your help !

I reformat my display by replacing my tables no div gold today my structure of an element this presents as well (See photo Capture.png):
link: https://drive.google.com/open?id=1OwHAn_rvfGeS73hIWg-M3IUKvGXvwmJZ

I have several information paragraph having the same syntax, with this format the problem is that if the content of my tag

is too long a white space this adds to the rest of my text so my second table (my second element with the syntax above) does not really appear afterwards but a large white space separates these two elements and I do not do not understand how to prevent this.

If you had an idea?

Yours,
Arshad

**Comment by spipu** [comment] 2019-02-19 16:03
duplicate of #424

**Closed by spipu** 2019-02-19 16:03 UTC
