### ISSUE TITLE
Image implementation not working

### ISSUE THREAD

**Issue by p-drolima** [spipu/html2pdf#380] opened 2018-09-19 10:29 UTC
Hi,

I have been trying to troubleshoot this issue with success and yes I did go through all other related issues to see if I could resolve this but unfortunately still not the result I want.

I am using this in a wordpress setup and calling the html directly on method to render the PDF and I get 2 different results on local and the production server. on local, I get no error log but and images do get passed to PDF but are white(not-visible), only the space filled in. This is true for any image type regardless. using http:// full path.

On the production environment I get the same results only the images are pinkish solid color, in other words they are there to fill in space but with a solid color.

I am wondering now if there is any thing server wise interfering with images being displayed properly. any insight would be greatly appreciated.

Best,

Pedro

**Comment by boileau** [comment] 2018-09-21 07:52
Same for me. Go back to earlier version of tcpdf to fix it (i try with succes with a 6.2.12 version).

**Comment by p-drolima** [comment] 2018-09-21 11:53
Part of me was inclined that was related to TCPDF. thanks boileau!

**Comment by p-drolima** [comment] 2018-09-21 16:50
do you happen to know why images are blurry? is there a way to make sure image render proper?

**Comment by spipu** [comment] 2018-09-24 13:00
did you tray with the last version of TCPDF ? (released 2 days ago)

**Comment by p-drolima** [comment] 2018-10-01 20:09
composer.json file and add the correct constraint > https://getcomposer.org/doc/articles/versions.md

Bear in mind that spipu did refer that last version should be tried first (6.2.25)

**Comment by spipu** [comment] 2018-10-26 08:29
duplicate of https://github.com/spipu/html2pdf/issues/383

**Closed by spipu** 2018-10-26 08:29 UTC
Labels: bug, duplicate
